### ISSUE TITLE
Plugins: command to print source info of the plugin

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise#504]
E.g. I want to contribute to one of the installed plugins. How/where should I do that?

IMO this could be included in the `bitrise plugin list` output directly, and/or maybe a `bitrise plugin info THEPLUGINID` to print infos about a specific plugin (e.g. `bitrise plugin info workflow-editor`).

**Comment by godrei** [comment]
Hi @viktorbenei , thanks for the issue.

We solved this in pr: https://github.com/bitrise-io/bitrise/pull/512

Bitrise-cli got a new command: `bitrise plugin info <plugin_name>`, which prints following infos:

```
Name: PLUGIN_NAME
Version: PLUGIN_VERSION
Source: PLUGIN_SOURCE
Definition: PLUGIN_DEFINITION (bitrise-plugin.yml content)
```

, since this info is not too much line of logs, `bitrise plugin list` prints the same infos about the installed plugins.
