### ISSUE TITLE
"Bitrise failed to unmarshal response body" when building with UI tetst?

### ISSUE THREAD

**Issue by Muddz** [bitrise-io/bitrise#543]
Whenever we try to make a build with Android Instrumental Ui test we get an error saying:
`Failed to unmarshal response body, error: [invalid character "F" looking for beginning of value Failed to get test status: INVALID(TEST_SAME_AS_APP)], body: %!s(MISSING)`

I'm not sure if the problem is from us or Bitrise's Golang server

![capture](https://user-images.githubusercontent.com/14817640/31602293-def0385a-b25c-11e7-8119-2a19a6b1b930.PNG)

**Comment by viktorbenei** [comment]
Hi,

The issue seems to be that you specified the same APK as the **APK path** input of the step, as well as the **Test APK path** input (under the **Instrumentation Test** section).

Running **Instrumentation** tests you need to provide both a non test (usually normal debug) APK **as well as** a test APK. Please see: https://blog.bitrise.io/introducing-solid-and-snappy-virtual-device-testing-for-android - **Instrumentation** section.

Let us know how it goes or if you'd need more info / further assistance! :)

**Comment by Muddz** [comment]
Thanks I solved it!

**Comment by viktorbenei** [comment]
Glad to hear that @Muddz , Happy Building! :)
