### ISSUE TITLE
Swapped lines order in CLI output

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise#582]
There is a script step with content like that:
```bash
cat <stripped>
openvpn --config vpn.conf &
disown -h %1

echo nameserver 10.8.0.1 > /etc/resolv.conf
echo nameserver 8.8.8.8 >> /etc/resolv.conf
```
Commands seem to be executed in that order, but log shows this:
```
+ cat
+ disown -h %1
+ openvpn --config vpn.conf
+ echo nameserver 10.8.0.1
+ echo nameserver 8.8.8.8
```
`disown` and `openvpn` commands are swapped.

Build URL: https://www.bitrise.io/build/04693754cc0fb063

**Comment by viktorbenei** [comment]
Thanks @koral-- for reporting! I believe we talked about this issue before, but can't find the issue, was probably not reported here but in another repo.. 

Anyway this issue seems to be related to Linux, specifically some kind of StdErr & StdOut buffering which happens behind the scenes (never seen this on macOS).

We're working on a couple of output / logging related tasks, which includes built-in buffered log outputs, I think that alone might solve this issue; will keep this issue open in the meantime.

**Comment by koral--** [comment]
Do you mean this one: https://github.com/bitrise-io/steps-git-clone/issues/63#issuecomment-353365828?
I remember, but that issue was about 2 interleaved logs: one generated by bitrise cli/step and another from underlying command. Order of lines originating from given source was correct.
Here, on the contrary we have only one source. So the reason may be different.

**Comment by viktorbenei** [comment]
Checked the build - the log (line order) I believe is not related to bitrise at all, but rather to Bash.

My guess is that the order is swapped because of `&` which starts the command async. I'm not 100% sure as I don't recall anything similar before, but the the lines starting with `+` are printed by Bash (`set -x` mode), so my best guess is that Bash itself evaluated / performed the async command later and that's why it printed it later in the log. (`set -v` prints the commands before evaluation, `set -x` prints *after* evalutation, *before* execution AFAIK).

**Comment by koral--** [comment]
Good catch. I've just checked it locally and commands executed in background (with `&`) are printed with `+` after the next foreground command.
