### ISSUE TITLE
Add BITRISE_CI and BITRISE_PR envrionment variables

### ISSUE THREAD

**Issue by patkub** [bitrise-io/bitrise#591]
It would be useful to add `BITRISE_CI` and `BITRISE_PR` environment variables that correspond to the existing `CI` and `PR` variables to aid in CI detection. Other continuous integration environments, such as CircleCI, also set `CI === true`, making it hard to detect the CI environment the code is running in.

This would be helpful for the [greenkeeper-lockfile project](https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/ci-services/tests.js#L12). If the Bitrise check was before the CircleCI check, CircleCI would run the bitrise code!

**Comment by viktorbenei** [comment]
Hi,

You're right, and it's actually possible now, but via an additional env var: https://devcenter.bitrise.io/faq/available-environment-variables/ -> `BITRISE_IO`

More details: The CLI itself should not and will not expose any such env var, because you can run the CLI anywhere, e.g. on your own Mac/Linux. Because of this the `CI`/`PR` env vars are exposed by the CLI but are **not** service specific, can not indicate which service the CLI is running in.

Instead, bitrise.io, the hosted service does set the additional `BITRISE_IO` env var, which will not be set by the CLI, so if you run the CLI on your own Mac that env var won't be set, but it will be set in every build which is performed by bitrise.io

I hope this helps, if you'd have any questions just let us know! ;)
