### ISSUE TITLE
No shared schemes found...

### ISSUE THREAD

**Issue by Aravindios** [bitrise-io/bitrise#606]
No shared schemes found...
The newly generated schemes, may differs from the ones in your project.
Make sure to share your schemes, to have the expected behaviour.

**Comment by BirmacherAkos** [comment]
Hi!

The most common cause of this issue is if you don't mark the scheme as shared. If you did, you should also check your gitignore list - shared schemes have to be stored in the git repository, the related files can't be ignored!

Related docs:
https://devcenter.bitrise.io/ios/frequent-ios-issues/#xcode-scheme-not-found

Don't forget to commit & push the changes if you just enabled the Shared option! 

If you still can't see the desired Scheme, try to look into your .gitignore file and check if you are ignoring the config files of your Xcode project.

**Comment by viktorbenei** [comment]
Closing this issue here as it's not related to the Bitrise CLI.

For build related issues please use the community forum: https://discuss.bitrise.io or report the issue to the related step's issue tracker. For tracking purposes we ask you to not to open issues here which are not related to the Bitrise CLI - but feel free to use any other channel, primarily https://discuss.bitrise.io email or the onsite chat on bitrise.io ! :)
