### ISSUE TITLE
【Android11】Signing step does not work properly and installation error

### ISSUE THREAD

**Issue by pa-hisayuki-kishino** [bitrise-io/bitrise#744]
We are linking bitrise and deploygate.
The bitrise sequence is complete.

At first glance it looks successful, When I try to install the apk downloaded from deploygate on an Android 11 device, the following error is displayed and the installation cannot be performed.

```
% adb install app-xxxx-release_dp230_bitrise.apk 
Performing Streamed Install
adb: failed to install app-xxxx-release_dp230_bitrise.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package net.xxxxxxxx.xxxx]
```

Similar result when installing apk of bitrise artifact.

**Comment by ofalvai** [comment]
Hi @pa-hisayuki-kishino,

Looking at the error message, this seems like a problem with the configuration of the Sign step (I assume you use our Android Sign step in your workflow). To get the APK signed with both a V1 and V2 signature, you need to use the `apksigner` tool instead of `jarsigner`. This option is called `Enable apksigner` on Bitrise (in the Sign step configuration)

You can read more about signing schemes [here](https://source.android.com/security/apksigning#schemes).

**Comment by pa-hisayuki-kishino** [comment]
Thanks! This issue has been solved by the above method!
