### ISSUE TITLE
Neither NewVersionCode nor NewVersionName are provided, however one of them is required.

### ISSUE THREAD

**Issue by ndbeyer** [bitrise-io/bitrise#755]
I have a workflow `myWorkFlow` that includes the `change-android-versioncode-and-versionname` step. 

When using `https://app.bitrise.io` this steps works just fine:

<img width="680" alt="grafik" src="https://user-images.githubusercontent.com/33200064/110447519-9b268080-80c0-11eb-95c1-56e5c9699827.png">

**In contrast** when using the `Bitrise CLI` after copying the `bitrise.yml` (including the `myWorkFlow` workflow), this step fails with the message `Neither NewVersionCode nor NewVersionName are provided, however one of them is required.`

Indeed, there is no `input variable` `new_version_code` setup in the `change-android-versioncode-and-versionname` in  `bitrise.yml`

<img width="510" alt="grafik" src="https://user-images.githubusercontent.com/33200064/110448205-43d4e000-80c1-11eb-9f9f-d416056cdd1c.png">

But I can see it in the UI on `https://app.bitrise.io`

<img width="1225" alt="grafik" src="https://user-images.githubusercontent.com/33200064/110448392-741c7e80-80c1-11eb-8021-63b4e22f8d1a.png">

So it appears, that `new_version_code` is not represented in the `bitrise.yml`.

Adding e.g. `new_version_code: 501` fixes the problem.

I think the `new_version_code` property should occur in the `bitrise.yml`

**Comment by ofalvai** [comment]
`NewVersionCode` is an input of the step, and your workflow is configured to assign the `$BITRISE_BUILD_NUMBER` environment variable to that step input. This env var is not available locally because it's exposed by Bitrise.io after starting your build ([see this list of env vars exposed by the CLI and Bitrise.io respectively](https://devcenter.bitrise.io/builds/available-environment-variables/))

If you want to keep using `$BITRISE_BUILD_NUMBER` on Bitrise.io and make it work locally too, we recommend using a template expression that assigns different values to the input in the two environments. There is a template expression at the bottom of this page: https://devcenter.bitrise.io/bitrise-cli/step-inputs/
