### ISSUE TITLE
AVD Manager can't boot

### ISSUE THREAD

**Issue by gelodgreat** [bitrise-io/bitrise#771]
AVD manager Failed to boot emulator device within 300 seconds.

This work previously but today it got issue on booting up

**Comment by cathyharmon** [comment]
Hello,

We discovered this issue yesterday and it appears to happen on stacks that are based on Catalina.  The issue appears to be due to a change to the emulator as reported at:

https://issuetracker.google.com/issues/191805460

We have reached out to Google to ask that this issue be prioritized.  IF you are affected by this issue, please visit the link and click the star icon to help increase the priority.

NOTE: This does not appear to affect the Big Sur based stacks.

- cathy
